skip_branch_with_pr: true

image: Ubuntu1804

environment:
  GH_TOKEN:
    secure: yVMCFepA5CWkd+a+SaL+RbAWaZ8SWQFzZKnd64SNt5PXEg704BRKWi4LWL08cSka

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.deb
- sudo dpkg -i ./hugo_extended_0.81.0_Linux-64bit.deb

build_script:
- hugo

deploy_script:
- bash release.sh
