relativeURLs = true
canonifyUrls = true
languageCode = "en-us"
layoutDir = "layouts"
contentdir = "content"
publishdir = "public"
baseURL = "https://markvincze.github.io/cookbook/"
title = "My Cookbook"
theme = "pixyll"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  search_engine = true
  paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
